# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
    };
  
  ## USB ZFS DAS
  boot.extraModprobeConfig = ''
    options zfs l2arc_write_max=10000000
    options zfs l2arc_noprefetch=0
  '';
  boot.kernelParams = [ "zfs.l2arc_rebuild_enabled=1" ];
  systemd.services.import-usb-das = {
    description = "Import USB DAS ZFS pool by ID";
    after = [ "local-fs.target" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      sleep 3
      # Attempt import using the specific ID and path that works
      if ! ${pkgs.zfs}/bin/zpool list | grep -q "storage-pool"; then
        ${pkgs.zfs}/bin/zpool import -d /dev/disk/by-path 9882993164348068333 storage-pool
        ${pkgs.zfs}/bin/zfs mount storage-pool || true
      fi
    '';
  };
  systemd.services.das-heartbeat = {
    description = "Keep USB zraid pool awake";
    # Only start if the ZFS pool is actually mounted
    after = [ "import-usb-das.service" ];
    serviceConfig = {
      Type = "oneshot";
      User = "root";
    };
    script = ''
      # Check if pool is healthy before touching
      if ${pkgs.zfs}/bin/zpool status storage-pool | grep -q "ONLINE"; then
        ${pkgs.coreutils}/bin/touch /storage-pool/.keepalive
        # Optional: Force a sync to ensure it hits the physical platters
        ${pkgs.coreutils}/bin/sync -f /storage-pool/.keepalive
      fi
    '';
  };
  systemd.timers.das-heartbeat = {
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "2m";
      OnUnitActiveSec = "5m"; # Beats the 10-minute Orico sleep timer
      Unit = "das-heartbeat.service";
    };
  };
  ##

  swapDevices = [ { device = "/.swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  powerManagement = {
    enable = true;
    cpuFreqGovernor = lib.mkDefault "powersave";
  };
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
